// TO DO:
// PROMPT THE USER TO IF THEY WANT BLUETOOTH OR AUDIO CORD 3.5MM 
// USE JAVA SOUND API, CAPTURE THE AUDIO STREAM AND PLAY THE CAPTURED AUDIO THROUGH THE SPEAKER
// ADD A BLUETOOTH SUPPORT USING BLUEALSA
public class caraux {
    
}
